version: '3'
services:
  prometheus:
    network_mode: "host"
    image: prom/prometheus:latest
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9090/-/healthy | grep -q 'Prometheus Server is Healthy'"]
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml      
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
      
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: "host"
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:3000/healthz | grep -i 'ok'"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes: 
      - "grafana-data:/var/lib/grafana"
      - "./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./dockercontainersmonitoring.json:/var/lib/grafana/dashboards/dockercontainersmonitoring.json"
      - "./Systemmonitoring.json:/var/lib/grafana/dashboards/Systemmonitoring.json"
      - "./default.yaml:/etc/grafana/provisioning/dashboards/default.yaml"
    privileged: true
    depends_on:
      - prometheus

volumes:
  grafana-data:
