global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['{{ hostvars["databases"]["ansible_host"] }}:9090']
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['{{ hostvars["controller"]["ansible_host"] }}:9100']
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['{{ hostvars["controller"]["ansible_host"] }}:8080']
