- name: STOP cAdvisor on source DB
  block:
    - name: docker compose up cadvisor  
      shell: |
        cd /home/{{ ansible_user }}/dmbench/
        docker compose down
  when: hostvars['db2-sourceDB'].ansible_host  != hostvars['controller'].ansible_host
  delegate_to: db2-sourceDB

- name: STOP cAdvisor on target DB
  block:
    - name: docker compose up cadvisor  
      shell: |
        cd /home/{{ ansible_user }}/dmbench/
        docker compose down
  when :  hostvars['db2-targetDB'].ansible_host  !=  hostvars['controller'].ansible_host 
  delegate_to: db2-targetDB

- name: Copy sourceDB docker compose file to the results folder
  ansible.builtin.copy:
    src: migrationengines/db2/databases/source/docker-compose.yml
    dest: "{{ resultsfolderpath.stdout }}/sourceDB-docker-compose.yml"
- name: Copy targetDB docker compose file to the results folder
  ansible.builtin.copy:
    src: migrationengines/db2/databases/target/docker-compose.yml
    dest: "{{ resultsfolderpath.stdout }}/targetDB-docker-compose.yml"

    