version: '3'
services:
  source:
    image: container-registry.oracle.com/mysql/community-server:8.0.32
    container_name: source
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - /home/fareshamouda/DataMigrationBenchmarkingTool/databaseMigration/my.cnf:/etc/my.cnf
      - /home/fareshamouda/DataMigrationBenchmarkingTool/databaseMigration/sourcedatadir:/var/lib/mysql
      - /home/fareshamouda/DataMigrationBenchmarkingTool/databaseMigration/sampledata/mysqlsampledatabase.sql:/tmp/mysqlsampledatabase.sql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
  target:
    image: container-registry.oracle.com/mysql/community-server:8.0.32
    container_name: target
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - /home/fareshamouda/DataMigrationBenchmarkingTool/databaseMigration/my.cnf:/etc/my.cnf
      - /home/fareshamouda/DataMigrationBenchmarkingTool/databaseMigration/targetdatadir:/var/lib/mysql
