services:
  db2source:
    image: icr.io/db2_community/db2
    container_name: db2source
    hostname: db2source
    restart: always
    privileged: true
    ports:
      - "50000:50000"
    env_file: .env_list
    volumes:
      - /home/ubuntu/database:/database
      - /home/ubuntu/generatedData:/data
      - /mnt:/largedata:ro