version: '3'
services:
  db2target:
    image: icr.io/db2_community/db2
    container_name: db2target
    hostname: db2Target
    restart: always
    # deploy:
    #     resources:
    #       limits:
    #         cpus: '0.05'
    #         memory: '5g'
    privileged: true
    volumes:
      - /home/ubuntu/db2target:/database
    ports:
      - "50000:50000"
    env_file: .env_list