version: '3'
services:
  db2target:
    image: icr.io/db2_community/db2
    container_name: db2target
    hostname: db2Target
    restart: always
    privileged: true
    volumes:
      - /home/{{ hostvars["db2-targetDB"]["ansible_user"] }}/db2target:/database
    ports:
      - "50000:50000"
    env_file: .env_list