name: CI/CD for DmBench

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  
    - name: Install dependencies for Config Parser Test
      run: |
        cd controller
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Config Parser Test
      run: |
        cd controller/tests
        python -m unittest testController.py
    - name: Install dependencies for Container Deployment Test
      run: |
        cd deployment/controller/tests
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Container Deployment Test
      run: |
        cd deployment/controller/tests
        python -m unittest testDeployment.py
    - name: Install dependencies for Kafka Logger Test
      run: |
        cd deployment/reporter/kafkacluster
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Kafka Logger Test
      run: |
        cd deployment/reporter/kafkacluster/test
        python -m unittest testLogger.py

        



