name: CI/CD for DmBench

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  
    - name: Install dependencies for Config Parser Test
      run: |
        cd controller
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Config Parser Test
      run: |
        cd controller/tests
        python -m unittest testController.py
    - name: Install dependencies for Container Deployment Test
      run: |
        cd deployment/controller/tests
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Container Deployment Test
      run: |
        cd deployment/controller/tests
        python -m unittest testDeployment.py
    - name: Install dependencies for Kafka Logger Test
      run: |
        cd deployment/reporter/kafkacluster
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Kafka Logger Test
      run: |
        cd deployment/reporter/kafkacluster/test
        python -m unittest testLogger.py
        
  build-and-push-docker:
    name: Build and Push Controller Docker Image
    runs-on: ubuntu-latest
    needs: test 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: {context}/controller/Dockerfile
          tags: 
 #           - fareshamouda/controller:latest
            - fareshamouda/controller:$(date +%Y%m%d%H%M%S)