name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd deployment/database
        docker compose up -d
    - name: Wait for Prometheus to be healthy
      run: |
        # Wait for Prometheus to be healthy
        docker -wait http://localhost:9090/-/healthy -timeout 1m
