name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd deployment/database
        docker compose up -d
    - name: Check container health
      run: |
        chmod +x ./.github/workflows/check_health.sh
        ./.github/workflows/check_health.sh prometheus
 
