name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd deployment/database
        docker compose up -d
    - name: Check container health
      run: |
        # Wait for Prometheus to be healthy
        HEALTH=$(docker inspect --format='{{json .State.Health}}' prometheus)
        STATUS=$(echo "$HEALTH" | jq -r '.Status')
        [ "$STATUS" == "healthy" ] || exit 1
